# https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3.8"
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:latest
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    environment:
      - TRUST_DOWNSTREAM_PROXY
    ports:
      - "80:80"
      - "443:443"
    tmpfs:
      - /var/run
      - /var/cache/nginx
      - /var/log/nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d

  letsencrypt:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion:latest
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs:rw
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
volumes:
  acme:
    name: acme
  certs:
    name: certs
  conf:
    name: conf
  html:
    name: html
  vhost:
    name: vhost

networks:
  default:
    name: nginx-proxy
