# https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3.8"
services:
  proxied-service:
    image: jwilder/whoami
    container_name: nginx-proxy-whoami
    restart: always
    environment:
      - VIRTUAL_PORT
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_TEST
      - LETSENCRYPT_EMAIL
    expose:
      - "${EXPOSE_PORT}"

networks:
  default:
    name: nginx-proxy
    # use pre-existing network from other docker-compose.yml
    external: true
