# https://docs.docker.com/compose/compose-file/compose-file-v3/

version: "3.8"
services:
  proxied-service:
    image: ${CONTAINER_IMAGE}
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
      - DEBUG=${LETSENCRYPT_DEBUG}
    expose:
      - "${EXPOSE_PORT}"
    networks:
      - nginx-automatic-proxy-network
    volumes:
      # These are provided for easy mounting of custom config files
      - conf:/conf.d
      - vhost:/vhost.d

volumes:
  conf:
    external: true
  vhost:
    external: true

networks:
  nginx-automatic-proxy-network:
    name: nginx-proxy
    # use pre-existing network from other docker-compose.yml
    external: true
